name: Issue Transferred

on:
  issues:
    types: [transferred]

permissions: {}

jobs:
  issue-transferred:
    name: Issue Transferred
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@384fd19694fe7b6dcc9a684746c6976ad78228ae # v1.1.1
        id: generate-token
        with:
          creds: ${{ secrets.ISSUE_TRIAGE_GH_APP_CREDS }}
          org: electron
      - name: Remove from issue triage
        uses: dsanders11/project-actions/delete-item@8bc0bd421be3a2f9e96e160c4cb703f97cd3be55 # v1.5.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          project-number: 90
